.gitmodules

Reverts Percona-Lab/pmm-submodules#75

Revert "Relative paths for SSH support."

---

.gitmodules

Reverts Percona-Lab/pmm-submodules#198

Revert "PMM-3681 Remove old qan-api."

---

build/bin/build-client-binary

Reverts Percona-Lab/pmm-submodules#231

Revert "PMM-3705 build pmm-managed with make release"

---

.gitmodules

That PR adds pmm submodule. It is not used yet, but it should fix build problems on Jenkins once this PR is merged, and other feature build PRs are rebased on top of new PMM-2.0 branch.

Add pmm submodules.

---

.gitmodules
build/bin/build-server-rpm

https://github.com/percona/pmm-server-packaging/pull/39

PMM-3837 Generate Swagger during the pmm-server build

---

Jenkinsfile

This PR will allow us to provide live feedback of the changes on API tests, The environment is created for the latest docker tag for this fb, It also adds notification to the build message on ci channel

PMM-4133 Testing Jenkins Changes

---

.gitmodules
build/pmm-server-docker/playbook-init.yml
build/pmm-server-docker/playbook-install.yml

https://github.com/Percona-Lab/percona-images/pull/23
https://github.com/percona/pmm-server/pull/141

PMM-4267 Install pg_stat_statement extension.

---

.gitmodules

https://github.com/Percona-Lab/pmm-submodules/pull/348

PMM-4232 change path to pmm-update repo

---

.gitmodules
build/pmm-server-docker/playbook-init.yml
build/pmm-server-docker/playbook-install.yml

https://github.com/percona/pmm-managed/pull/234
See also https://github.com/Percona-Lab/percona-images/pull/31.

PMM-2301 Disable anonymous access.

---

.gitmodules
build/pmm-server-docker/playbook-install.yml

PMM-4550 Update PG to PG11 inside PMMserver

---

build/bin/Dockerfile
build/bin/build-server-docker

https://github.com/Percona-Lab/pmm-submodules/pull/421

PMM-4518 Use ansible playbooks from 'percona-images' repo

---

.gitmodules
Jenkinsfile
build/bin/build-server

PMM-4452 Remove pmm-configurator.

---

build/config/pmm-agent.logrotate

Reverts Percona-Lab/pmm-submodules#512

Revert "JEN-1165 test build"

---

build/rpmbuild-docker/Dockerfile

Updated node.js version to 12 for rpmbuild docker image

PMM-5402 node.js 12 rpmbuild

---

build/rpmbuild-docker/Dockerfile

Added yarnpkg for rpmbuild docker image

PMM-5400 yarnpkg for rpmbuild

---

build/bin/build-server-rpm
build/rpmbuild-docker/Dockerfile

PMM-5329 Update Prometheus to version 2.16.0

---

build/bin/build-client-deb

Disable interactive front-end for Debian-based distros during package installation/upgrade.

PMM-5403 Non-interactive FE for Debian-like distros

---

build/bin/build-client-deb

Ubuntu 20.04 support for PMM1 client
---
Dependent PR's:
FB test pipeline: [pmm.cd](https://pmm.cd.percona.com/job/ubuntu2004-pmm1-client/)

PMM-5665 [FB] PMM1 Ubuntu 20.04 support

---

build/bin/build-client-packages
build/bin/build-client-rpm

Ubuntu 20.04 support for PMM2 client
---
Dependent PR's:
FB test pipeline: [pmm.cd](https://pmm.cd.percona.com/job/ubuntu2004-pmm2-client/)

PMM-5403 [FB] PMM2 Ubuntu 20.04 support

---

Jenkinsfile

PMM-5767 Test with new UI job and Playwright

---

build/bin/build-server-rpm
build/bin/prepare-node-modules

Updated grafana to 6.7.3
---
Related PRs:

PMM-5549 [FB] Grafana 6.7.3

---

build/bin/build-client-packages
build/rpmbuild-docker/Dockerfile

https://jira.percona.com/browse/PMM-5645
Related PR https://github.com/Percona-Lab/pmm-submodules/pull/910

PMM-5645 Build with go v1.14.4

---

build/pmm-server-docker/Dockerfile
build/rpmbuild-docker/Dockerfile

- **pmm-server** Dockerfile: create `/.pmm-docker` inside server image
- **rpmbuild** Dockerfile: install `golang` from **epel**, and `nodejs 8` from **official repo**

PMM-5813 Modified Dockerfiles

---

build/bin/build-client-deb
build/bin/build-client-sdeb

Removed Debian Jessie (EOL) from build scripts

PMM-6311 removed debian jessie from build scripts

---

Jenkinsfile
build/bin/build-server

Do not rewind – that PR should actually be merged.

PMM-6119 Build dbaas-controller

---

.gitmodules
build/bin/build-client-binary
build/bin/install_tarball
build/rpm/pmm2-client.spec

PMM-5701 DB_Uptime in Home Dashboard shows wrong metric

---

build/rpmbuild-docker/Dockerfile

PMM-6212 Add goreleaser installation to docker image

---

Jenkinsfile
build/bin/build-server

Rebased from https://github.com/Percona-Lab/pmm-submodules/pull/1069

 PMM-6212: Package dbaas-tools

---

Jenkinsfile

Added **errexit** and **xtrace** for multiline shell steps
Related PRs:
- [jenkins-pipelines](https://github.com/Percona-Lab/jenkins-pipelines/pull/540)
Blocked by: [PMM-6516](https://github.com/Percona-Lab/pmm-submodules/pull/1043)

PMM-6410 errexit & xtrace

---

build/pmm-client-docker/entrypoint.py

It is needed now for PoCs and SaaS monitoring.

PMM-6633 Add PMM_AGENT_ENTRYPOINT_DELAY.

---

Jenkinsfile

Add link for Staging Job with Server Client Tags

---

build/bin/vars

with vmdb https://github.com/Percona-Lab/pmm-submodules/pull/1257

updates vmagent

---

Jenkinsfile

[PMM-6982](https://jira.percona.com/browse/PMM-6982)
https://github.com/percona/pmm-managed/pull/564
https://github.com/Percona-Lab/jenkins-pipelines/pull/681
https://github.com/Percona-Lab/pmm-submodules/pull/1286

PMM-6982 Remove PERCONA_TEST_IA.

---

build/bin/vars

FB: https://github.com/Percona-Lab/pmm-submodules/pull/1319
Other PRs
https://github.com/percona/pmm-server-packaging/pull/186

PMM-7173 Update VMAgent

---

build/bin/vars

FB -> https://github.com/Percona-Lab/pmm-submodules/pull/1348

PMM-7135 Update VMAgent

---

build/bin/vars

PMM-7471 Update VictoriaMetrics used inside PMM from 1.52.0 to 1.53.1

---

.gitmodules
Jenkinsfile
build/bin/build-server
build/bin/prepare-node-modules

Relevant PRs:
- https://github.com/percona/pmm-server/pull/244
- https://github.com/percona/pmm-server-packaging/pull/196
- https://github.com/Percona-Lab/jenkins-pipelines/pull/745
- https://github.com/Percona-Lab/percona-images/pull/97
- https://github.com/percona/pmm/pull/658
- https://github.com/percona/grafana-dashboards/pull/1097
- https://github.com/percona/pmm-update/pull/116
- https://github.com/percona/pmm-managed/pull/668

PMM-6766 remove qan-app

---

.gitmodules
build/bin/build-client-binary
build/bin/build-client-packages
build/bin/build-client-source
build/debian/files
build/debian/install
build/debian/rules
build/rpm/pmm2-client.spec

PMM-7691 add azure_exporter into pmm2-client

---

.gitmodules
Jenkinsfile
build/bin/create-tags.py
build/bin/vars

https://jira.percona.com/browse/PMM-6017

PMM-6017 merge pmm-server-packaging to pmm-server

---

.gitmodules
Jenkinsfile

https://jira.percona.com/browse/PMM-7874

PMM-7874 UI tests migration
